# Generated by Django 5.1.1 on 2024-09-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_options_alter_payment_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("Cash", "наличные"), ("Transfer", "перевод ")],
                max_length=50,
                verbose_name="тип оплаты",
            ),
        ),
    ]
