# Generated by Django 5.1.1 on 2024-09-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_picture",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку курса",
                null=True,
                upload_to="materials/photo",
                verbose_name="Превью курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_picture",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку урока",
                null=True,
                upload_to="materials/photo",
                verbose_name="Превью урока",
            ),
        ),
    ]
